import type { McpConnectorSpec } from "@/types/mcp";

export const MCP_CATALOG_LOCAL: McpConnectorSpec[] = [
  {
    id: "context7", display_name: "Context7", category: "devtools", auth_type: "none",
    short_descriptions: {
      fr: "Documentation et exemples de code à jour pour 1000+ librairies.",
      en: "Up-to-date docs and code examples for 1000+ libraries.",
      es: "Documentación y ejemplos de código actualizados para más de 1000 librerías.",
      de: "Aktuelle Dokumentation und Codebeispiele für über 1000 Bibliotheken.",
      it: "Documentazione ed esempi di codice aggiornati per oltre 1000 librerie.",
      zh: "为 1000 多个库提供最新文档和代码示例。",
      ja: "1000 以上のライブラリ向けの最新ドキュメントとコード例。",
    },
    author: "Upstash", url: "https://context7.com",
    install_command: "npx @upstash/context7-mcp@2.2.5",
    tools: ["resolve_library_id", "query_docs"],
  },
  {
    id: "huggingface", display_name: "Hugging Face", category: "ai-ml", auth_type: "token",
    short_descriptions: {
      fr: "Explorer les modèles, datasets, Spaces et papers du Hub.",
      en: "Explore Hub models, datasets, Spaces and papers.",
      es: "Explora modelos, datasets, Spaces y papers del Hub.",
      de: "Modelle, Datasets, Spaces und Papers im Hub durchsuchen.",
      it: "Esplora modelli, dataset, Spaces e paper dell'Hub.",
      zh: "浏览 Hub 的模型、数据集、Spaces 和论文。",
      ja: "Hub のモデル、データセット、Spaces、論文を探索。",
    },
    author: "Hugging Face", url: "https://huggingface.co/mcp",
    install_command: "npx @llmindset/hf-mcp-server@0.3.13",
    env_keys: ["HF_TOKEN"],
    tools: ["model_search", "dataset_search", "spaces_search", "papers_search", "docs_search"],
  },
  {
    id: "imessage", display_name: "iMessage", category: "communication", auth_type: "none",
    short_descriptions: {
      fr: "Accès lecture-seule aux conversations iMessage.",
      en: "Read-only access to iMessage conversations.",
      es: "Acceso de solo lectura a conversaciones de iMessage.",
      de: "Schreibgeschützter Zugriff auf iMessage-Unterhaltungen.",
      it: "Accesso in sola lettura alle conversazioni iMessage.",
      zh: "只读访问 iMessage 对话。",
      ja: "iMessage の会話への読み取り専用アクセス。",
    },
    author: "Wyatt Johnson", url: "https://github.com/wyattjoh/imessage-mcp",
    install_command: "deno run --allow-read --allow-env --allow-sys --allow-ffi jsr:@wyattjoh/imessage-mcp@0.4.2",
    os_restrict: "macos",
    tools: ["search_messages", "get_recent_messages", "get_chats", "get_messages_from_chat"],
  },
  {
    id: "producthunt", display_name: "Product Hunt", category: "community", auth_type: "token",
    short_descriptions: {
      fr: "Accès aux posts, collections et topics Product Hunt.",
      en: "Access Product Hunt posts, collections and topics.",
      es: "Accede a posts, colecciones y temas de Product Hunt.",
      de: "Zugriff auf Product-Hunt-Posts, Sammlungen und Themen.",
      it: "Accedi a post, raccolte e topic di Product Hunt.",
      zh: "访问 Product Hunt 的帖子、合集和主题。",
      ja: "Product Hunt の投稿、コレクション、トピックにアクセス。",
    },
    author: "Jai Pandya", url: "https://www.producthunt.com",
    install_command: "uvx product-hunt-mcp==0.1.0",
    env_keys: ["PRODUCT_HUNT_TOKEN"],
    tools: ["get_posts", "get_post_details", "get_collections", "search_topics", "get_user"],
  },
  {
    id: "reddit", display_name: "Reddit", category: "community", auth_type: "none",
    short_descriptions: {
      fr: "Lecture et écriture Reddit : posts, commentaires, trending.",
      en: "Read and write Reddit: posts, comments, trending.",
      es: "Lee y escribe en Reddit: posts, comentarios y tendencias.",
      de: "Reddit lesen und schreiben: Posts, Kommentare, Trends.",
      it: "Leggi e scrivi su Reddit: post, commenti e trend.",
      zh: "读写 Reddit：帖子、评论和热门内容。",
      ja: "Reddit の投稿、コメント、トレンドを読み書き。",
    },
    author: "Jordan Burke", url: "https://www.reddit.com",
    install_command: "npx reddit-mcp-server@1.4.5",
    tools: ["read_posts", "search", "trending", "create_post", "reply", "edit"],
  },
];
