import type { McpConnectorSpec } from "@/types/mcp";

export const MCP_CATALOG_CLOUD: McpConnectorSpec[] = [
  {
    id: "gmail", display_name: "Gmail", category: "communication", auth_type: "oauth",
    short_description: "Accès sécurisé à Gmail : brouillons, labels, recherche.",
    short_description_en: "Secure Gmail access: drafts, labels, search.",
    author: "Google Cloud", url: "https://mail.google.com",
    endpoint: "https://gmailmcp.googleapis.com/mcp/v1",
    tools: ["draft_create", "read_mail", "search_mail", "label_manage"],
    coming_soon: true,
  },
  {
    id: "google-drive", display_name: "Google Drive", category: "productivity", auth_type: "oauth",
    short_description: "Recherche, lecture et écriture de fichiers Google Drive.",
    short_description_en: "Search, read and write Google Drive files.",
    author: "Google Cloud", url: "https://drive.google.com",
    endpoint: "https://drivemcp.googleapis.com/mcp/v1",
    tools: ["list_files", "search_files", "read_doc", "write_doc", "file_ops"],
    coming_soon: true,
  },
  {
    id: "google-calendar", display_name: "Google Calendar", category: "productivity", auth_type: "oauth",
    short_description: "Gestion des événements, disponibilités et réunions.",
    short_description_en: "Manage events, availability and meetings.",
    author: "Google Cloud", url: "https://calendar.google.com",
    endpoint: "https://calendarmcp.googleapis.com/mcp/v1",
    tools: ["list_calendars", "create_event", "update_event", "delete_event", "check_freebusy"],
    coming_soon: true,
  },
  {
    id: "canva", display_name: "Canva", category: "design", auth_type: "oauth",
    short_description: "Créer, éditer et exporter des designs Canva.",
    short_description_en: "Create, edit and export Canva designs.",
    author: "Canva", url: "https://www.canva.com",
    endpoint: "https://mcp.canva.com/mcp",
    tools: ["generate_design", "search_designs", "get_design", "update_design", "export_design"],
  },
  {
    id: "figma", display_name: "Figma", category: "design", auth_type: "oauth",
    short_description: "Accès aux designs Figma, tokens et génération de code.",
    short_description_en: "Access Figma designs, tokens and code generation.",
    author: "Figma", url: "https://www.figma.com",
    endpoint: "https://mcp.figma.com/mcp",
    tools: ["use_figma", "search_design_system", "create_file", "get_variables", "get_code_connect"],
  },
  {
    id: "notion", display_name: "Notion", category: "productivity", auth_type: "oauth",
    short_description: "Lire, écrire et chercher dans vos pages et bases Notion.",
    short_description_en: "Read, write and search your Notion pages and databases.",
    author: "Notion Labs", url: "https://www.notion.so",
    endpoint: "https://mcp.notion.com/mcp",
    tools: ["create_page", "update_page", "search", "query_database", "add_comment", "manage_blocks"],
  },
  {
    id: "slack", display_name: "Slack", category: "communication", auth_type: "oauth",
    short_description: "Recherche de messages, envoi et gestion de canaux Slack.",
    short_description_en: "Search messages, send and manage Slack channels.",
    author: "Slack API", url: "https://slack.com",
    endpoint: "https://mcp.slack.com/mcp",
    tools: ["search_messages", "send_message", "manage_canvases", "get_user_info", "get_channel_info"],
  },
  {
    id: "linear", display_name: "Linear", category: "devtools", auth_type: "oauth",
    short_description: "Gestion des issues, projets et sprints Linear.",
    short_description_en: "Manage Linear issues, projects and sprints.",
    author: "Linear", url: "https://linear.app",
    endpoint: "https://mcp.linear.app/mcp",
    tools: ["find_issues", "create_issue", "update_issue", "get_projects", "create_comment"],
  },
  {
    id: "lucid", display_name: "Lucid", category: "design", auth_type: "oauth",
    short_description: "Accès aux diagrammes Lucidchart et boards Lucidspark.",
    short_description_en: "Access Lucidchart diagrams and Lucidspark boards.",
    author: "Lucid Software", url: "https://lucid.app",
    endpoint: "https://mcp.lucid.app",
    tools: ["search_documents", "get_document", "create_diagram", "edit_document", "share_document"],
  },
  {
    id: "sentry", display_name: "Sentry", category: "devtools", auth_type: "oauth",
    short_description: "Recherche d'erreurs, détails issues et analyse Seer.",
    short_description_en: "Search errors, issue details and Seer analysis.",
    author: "Sentry", url: "https://sentry.io",
    endpoint: "https://mcp.sentry.dev/mcp",
    tools: ["search_issues", "get_issue_details", "search_events", "find_projects", "find_releases"],
  },
  {
    id: "vercel", display_name: "Vercel", category: "devtools", auth_type: "oauth",
    short_description: "Gestion des déploiements, logs et domaines Vercel.",
    short_description_en: "Manage Vercel deployments, logs and domains.",
    author: "Vercel", url: "https://vercel.com",
    endpoint: "https://mcp.vercel.com",
    tools: ["list_projects", "list_deployments", "get_build_logs", "get_runtime_logs", "deploy"],
  },
  {
    id: "apify", display_name: "Apify", category: "scraping", auth_type: "oauth",
    short_description: "Extraction de données web via scrapers et crawlers Apify.",
    short_description_en: "Web data extraction via Apify scrapers and crawlers.",
    author: "Apify", url: "https://apify.com",
    endpoint: "https://mcp.apify.com",
    tools: ["search_actors", "call_actor", "fetch_actor_details", "dataset_retrieval"],
  },
  {
    id: "github", display_name: "GitHub", category: "devtools", auth_type: "oauth",
    short_description: "Gestion complète GitHub : repos, issues, PRs, CI/CD.",
    short_description_en: "Full GitHub management: repos, issues, PRs, CI/CD.",
    author: "GitHub", url: "https://github.com",
    endpoint: "https://api.githubcopilot.com/mcp/",
    tools: ["list_repos", "create_issue", "create_pr", "get_file", "search_code", "list_workflows"],
  },
];
