import type { McpConnectorSpec } from "@/types/mcp";

export const MCP_CATALOG_CLOUD: McpConnectorSpec[] = [
  {
    id: "gmail", display_name: "Gmail", category: "communication", auth_type: "oauth",
    short_descriptions: { fr: "Accès sécurisé à Gmail : brouillons, labels, recherche.", en: "Secure Gmail access: drafts, labels, search.", es: "Acceso seguro a Gmail: borradores, etiquetas y búsqueda.", de: "Sicherer Gmail-Zugriff: Entwürfe, Labels und Suche.", it: "Accesso sicuro a Gmail: bozze, etichette e ricerca.", zh: "安全访问 Gmail：草稿、标签和搜索。", ja: "Gmail への安全なアクセス：下書き、ラベル、検索。" },
    author: "Google Cloud", url: "https://mail.google.com",
    endpoint: "https://gmailmcp.googleapis.com/mcp/v1",
    tools: ["draft_create", "read_mail", "search_mail", "label_manage"],
    coming_soon: true,
  },
  {
    id: "google-drive", display_name: "Google Drive", category: "productivity", auth_type: "oauth",
    short_descriptions: {
      fr: "Recherche, lecture et écriture de fichiers Google Drive.",
      en: "Search, read and write Google Drive files.",
      es: "Busca, lee y escribe archivos de Google Drive.",
      de: "Google-Drive-Dateien suchen, lesen und schreiben.",
      it: "Cerca, leggi e scrivi file su Google Drive.",
      zh: "搜索、读取和写入 Google Drive 文件。",
      ja: "Google Drive ファイルの検索、読み取り、書き込み。",
    },
    author: "Google Cloud", url: "https://drive.google.com",
    endpoint: "https://drivemcp.googleapis.com/mcp/v1",
    tools: ["list_files", "search_files", "read_doc", "write_doc", "file_ops"],
    coming_soon: true,
  },
  {
    id: "google-calendar", display_name: "Google Calendar", category: "productivity", auth_type: "oauth",
    short_descriptions: {
      fr: "Gestion des événements, disponibilités et réunions.",
      en: "Manage events, availability and meetings.",
      es: "Gestiona eventos, disponibilidad y reuniones.",
      de: "Termine, Verfügbarkeiten und Meetings verwalten.",
      it: "Gestisci eventi, disponibilità e riunioni.",
      zh: "管理日程、空闲时间和会议。",
      ja: "予定、空き時間、会議を管理。",
    },
    author: "Google Cloud", url: "https://calendar.google.com",
    endpoint: "https://calendarmcp.googleapis.com/mcp/v1",
    tools: ["list_calendars", "create_event", "update_event", "delete_event", "check_freebusy"],
    coming_soon: true,
  },
  {
    id: "canva", display_name: "Canva", category: "design", auth_type: "oauth",
    short_descriptions: {
      fr: "Créer, éditer et exporter des designs Canva.",
      en: "Create, edit and export Canva designs.",
      es: "Crea, edita y exporta diseños de Canva.",
      de: "Canva-Designs erstellen, bearbeiten und exportieren.",
      it: "Crea, modifica ed esporta design Canva.",
      zh: "创建、编辑和导出 Canva 设计。",
      ja: "Canva デザインの作成、編集、書き出し。",
    },
    author: "Canva", url: "https://www.canva.com",
    endpoint: "https://mcp.canva.com/mcp",
    tools: ["generate_design", "search_designs", "get_design", "update_design", "export_design"],
  },
  {
    id: "figma", display_name: "Figma", category: "design", auth_type: "oauth",
    short_descriptions: {
      fr: "Accès aux designs Figma, tokens et génération de code.",
      en: "Access Figma designs, tokens and code generation.",
      es: "Accede a diseños Figma, tokens y generación de código.",
      de: "Zugriff auf Figma-Designs, Tokens und Codegenerierung.",
      it: "Accedi a design Figma, token e generazione di codice.",
      zh: "访问 Figma 设计、令牌和代码生成。",
      ja: "Figma デザイン、トークン、コード生成にアクセス。",
    },
    author: "Figma", url: "https://www.figma.com",
    endpoint: "https://mcp.figma.com/mcp",
    tools: ["use_figma", "search_design_system", "create_file", "get_variables", "get_code_connect"],
  },
  {
    id: "notion", display_name: "Notion", category: "productivity", auth_type: "oauth",
    short_descriptions: {
      fr: "Lire, écrire et chercher dans vos pages et bases Notion.",
      en: "Read, write and search your Notion pages and databases.",
      es: "Lee, escribe y busca en páginas y bases de datos de Notion.",
      de: "Notion-Seiten und Datenbanken lesen, schreiben und durchsuchen.",
      it: "Leggi, scrivi e cerca in pagine e database Notion.",
      zh: "读取、写入和搜索 Notion 页面与数据库。",
      ja: "Notion ページとデータベースの読み書き、検索。",
    },
    author: "Notion Labs", url: "https://www.notion.so",
    endpoint: "https://mcp.notion.com/mcp",
    tools: ["create_page", "update_page", "search", "query_database", "add_comment", "manage_blocks"],
  },
  {
    id: "slack", display_name: "Slack", category: "communication", auth_type: "oauth",
    short_descriptions: {
      fr: "Recherche de messages, envoi et gestion de canaux Slack.",
      en: "Search messages, send and manage Slack channels.",
      es: "Busca mensajes, envía y gestiona canales de Slack.",
      de: "Slack-Nachrichten suchen, senden und Kanäle verwalten.",
      it: "Cerca messaggi, invia e gestisci canali Slack.",
      zh: "搜索消息、发送消息并管理 Slack 频道。",
      ja: "Slack メッセージの検索、送信、チャンネル管理。",
    },
    author: "Slack API", url: "https://slack.com",
    endpoint: "https://mcp.slack.com/mcp",
    tools: ["search_messages", "send_message", "manage_canvases", "get_user_info", "get_channel_info"],
  },
  {
    id: "linear", display_name: "Linear", category: "devtools", auth_type: "oauth",
    short_descriptions: {
      fr: "Gestion des issues, projets et sprints Linear.",
      en: "Manage Linear issues, projects and sprints.",
      es: "Gestiona issues, proyectos y sprints de Linear.",
      de: "Linear-Issues, Projekte und Sprints verwalten.",
      it: "Gestisci issue, progetti e sprint Linear.",
      zh: "管理 Linear 问题、项目和冲刺。",
      ja: "Linear の課題、プロジェクト、スプリントを管理。",
    },
    author: "Linear", url: "https://linear.app",
    endpoint: "https://mcp.linear.app/mcp",
    tools: ["find_issues", "create_issue", "update_issue", "get_projects", "create_comment"],
  },
  {
    id: "lucid", display_name: "Lucid", category: "design", auth_type: "oauth",
    short_descriptions: {
      fr: "Accès aux diagrammes Lucidchart et boards Lucidspark.",
      en: "Access Lucidchart diagrams and Lucidspark boards.",
      es: "Accede a diagramas Lucidchart y tableros Lucidspark.",
      de: "Zugriff auf Lucidchart-Diagramme und Lucidspark-Boards.",
      it: "Accedi a diagrammi Lucidchart e board Lucidspark.",
      zh: "访问 Lucidchart 图表和 Lucidspark 白板。",
      ja: "Lucidchart 図と Lucidspark ボードにアクセス。",
    },
    author: "Lucid Software", url: "https://lucid.app",
    endpoint: "https://mcp.lucid.app",
    tools: ["search_documents", "get_document", "create_diagram", "edit_document", "share_document"],
  },
  {
    id: "sentry", display_name: "Sentry", category: "devtools", auth_type: "oauth",
    short_descriptions: {
      fr: "Recherche d'erreurs, détails issues et analyse Seer.",
      en: "Search errors, issue details and Seer analysis.",
      es: "Busca errores, detalles de issues y análisis Seer.",
      de: "Fehler suchen, Issue-Details und Seer-Analysen abrufen.",
      it: "Cerca errori, dettagli issue e analisi Seer.",
      zh: "搜索错误、问题详情和 Seer 分析。",
      ja: "エラー検索、課題詳細、Seer 分析。",
    },
    author: "Sentry", url: "https://sentry.io",
    endpoint: "https://mcp.sentry.dev/mcp",
    tools: ["search_issues", "get_issue_details", "search_events", "find_projects", "find_releases"],
  },
  {
    id: "vercel", display_name: "Vercel", category: "devtools", auth_type: "oauth",
    short_descriptions: {
      fr: "Gestion des déploiements, logs et domaines Vercel.",
      en: "Manage Vercel deployments, logs and domains.",
      es: "Gestiona despliegues, logs y dominios de Vercel.",
      de: "Vercel-Deployments, Logs und Domains verwalten.",
      it: "Gestisci deploy, log e domini Vercel.",
      zh: "管理 Vercel 部署、日志和域名。",
      ja: "Vercel のデプロイ、ログ、ドメインを管理。",
    },
    author: "Vercel", url: "https://vercel.com",
    endpoint: "https://mcp.vercel.com",
    tools: ["list_projects", "list_deployments", "get_build_logs", "get_runtime_logs", "deploy"],
  },
  {
    id: "apify", display_name: "Apify", category: "scraping", auth_type: "oauth",
    short_descriptions: {
      fr: "Extraction de données web via scrapers et crawlers Apify.",
      en: "Web data extraction via Apify scrapers and crawlers.",
      es: "Extrae datos web con scrapers y crawlers de Apify.",
      de: "Webdaten über Apify-Scraper und Crawler extrahieren.",
      it: "Estrai dati web con scraper e crawler Apify.",
      zh: "通过 Apify 爬虫和抓取器提取网页数据。",
      ja: "Apify のスクレイパーとクローラーで Web データを抽出。",
    },
    author: "Apify", url: "https://apify.com",
    endpoint: "https://mcp.apify.com",
    tools: ["search_actors", "call_actor", "fetch_actor_details", "dataset_retrieval"],
  },
  {
    id: "github", display_name: "GitHub", category: "devtools", auth_type: "oauth",
    short_descriptions: {
      fr: "Gestion complète GitHub : repos, issues, PRs, CI/CD.",
      en: "Full GitHub management: repos, issues, PRs, CI/CD.",
      es: "Gestión completa de GitHub: repos, issues, PRs y CI/CD.",
      de: "Vollständige GitHub-Verwaltung: Repos, Issues, PRs, CI/CD.",
      it: "Gestione completa GitHub: repo, issue, PR e CI/CD.",
      zh: "完整管理 GitHub：仓库、问题、PR 和 CI/CD。",
      ja: "GitHub を包括管理：リポジトリ、課題、PR、CI/CD。",
    },
    author: "GitHub", url: "https://github.com",
    endpoint: "https://api.githubcopilot.com/mcp/",
    tools: ["list_repos", "create_issue", "create_pr", "get_file", "search_code", "list_workflows"],
  },
];
