use super::{ForecastModelSpec, ForecastProviderSpec};

pub const FORECAST_PROVIDERS: &[ForecastProviderSpec] = &[
    ForecastProviderSpec {
        id: "chronos",
        display_name: "Amazon Chronos",
        category: "forecast",
        base_url: "http://localhost:12000",
        signup_url: "https://huggingface.co/amazon/chronos-2",
        free_tier_label: "Local",
        short_description: "Modèles locaux de séries temporelles Amazon — Apache 2.0.",
        short_description_en: "Amazon local time series models — Apache 2.0.",
        requires_api_key: false,
    },
    ForecastProviderSpec {
        id: "nixtla",
        display_name: "Nixtla (TimeGPT-2)",
        category: "forecast",
        base_url: "https://api.nixtla.io",
        signup_url: "https://dashboard.nixtla.io",
        free_tier_label: "$1000 credits",
        short_description: "TimeGPT-2 cloud — $1000 crédits offerts.",
        short_description_en: "TimeGPT-2 cloud — $1000 free credits.",
        requires_api_key: true,
    },
];

pub const FORECAST_MODELS: &[ForecastModelSpec] = &[
    ForecastModelSpec {
        id: "chronos-bolt-tiny",
        provider_id: "chronos",
        display_name: "Chronos-Bolt Tiny",
        params: "9M",
        size_mb: 35,
        ram_mb: 150,
        vram_mb: Some(60),
        cpu_supported: true,
        gpu_supported: true,
        multivariate: false,
        covariates: false,
        horizon_max: 1000,
        frequencies: "10S à Y",
        hf_repo: Some("amazon/chronos-bolt-tiny"),
        is_cloud: false,
    },
    ForecastModelSpec {
        id: "chronos-bolt-mini",
        provider_id: "chronos",
        display_name: "Chronos-Bolt Mini",
        params: "21M",
        size_mb: 85,
        ram_mb: 350,
        vram_mb: Some(120),
        cpu_supported: true,
        gpu_supported: true,
        multivariate: false,
        covariates: false,
        horizon_max: 1000,
        frequencies: "10S à Y",
        hf_repo: Some("amazon/chronos-bolt-mini"),
        is_cloud: false,
    },
    ForecastModelSpec {
        id: "chronos-bolt-small",
        provider_id: "chronos",
        display_name: "Chronos-Bolt Small",
        params: "48M",
        size_mb: 191,
        ram_mb: 750,
        vram_mb: Some(280),
        cpu_supported: true,
        gpu_supported: true,
        multivariate: false,
        covariates: false,
        horizon_max: 1000,
        frequencies: "10S à Y",
        hf_repo: Some("amazon/chronos-bolt-small"),
        is_cloud: false,
    },
    ForecastModelSpec {
        id: "chronos-bolt-base",
        provider_id: "chronos",
        display_name: "Chronos-Bolt Base",
        params: "205M",
        size_mb: 821,
        ram_mb: 3200,
        vram_mb: Some(1200),
        cpu_supported: true,
        gpu_supported: true,
        multivariate: false,
        covariates: false,
        horizon_max: 1000,
        frequencies: "10S à Y",
        hf_repo: Some("amazon/chronos-bolt-base"),
        is_cloud: false,
    },
    ForecastModelSpec {
        id: "chronos-2",
        provider_id: "chronos",
        display_name: "Chronos-2",
        params: "120M",
        size_mb: 478,
        ram_mb: 2400,
        vram_mb: Some(1000),
        cpu_supported: true,
        gpu_supported: true,
        multivariate: false,
        covariates: false,
        horizon_max: 1024,
        frequencies: "10S à Y",
        hf_repo: Some("amazon/chronos-2"),
        is_cloud: false,
    },
    ForecastModelSpec {
        id: "timegpt-2-mini",
        provider_id: "nixtla",
        display_name: "TimeGPT-2 Mini",
        params: "—",
        size_mb: 0,
        ram_mb: 0,
        vram_mb: None,
        cpu_supported: false,
        gpu_supported: false,
        multivariate: true,
        covariates: true,
        horizon_max: 5000,
        frequencies: "T à Y",
        hf_repo: None,
        is_cloud: true,
    },
    ForecastModelSpec {
        id: "timegpt-2-standard",
        provider_id: "nixtla",
        display_name: "TimeGPT-2 Standard",
        params: "—",
        size_mb: 0,
        ram_mb: 0,
        vram_mb: None,
        cpu_supported: false,
        gpu_supported: false,
        multivariate: true,
        covariates: true,
        horizon_max: 5000,
        frequencies: "T à Y",
        hf_repo: None,
        is_cloud: true,
    },
    ForecastModelSpec {
        id: "timegpt-2-pro",
        provider_id: "nixtla",
        display_name: "TimeGPT-2 Pro",
        params: "—",
        size_mb: 0,
        ram_mb: 0,
        vram_mb: None,
        cpu_supported: false,
        gpu_supported: false,
        multivariate: true,
        covariates: true,
        horizon_max: 5000,
        frequencies: "T à Y",
        hf_repo: None,
        is_cloud: true,
    },
];
