pub mod advanced;
pub mod auto_selection;
pub mod auto_selection_ui;
pub mod catalog;
pub mod client_chronos;
mod client_http;
mod client_local_response;
mod client_local_structured;
pub mod client_nixtla;
mod client_nixtla_options;
mod client_nixtla_retry;
mod client_quantiles;
pub mod data_fingerprint;
mod data_profile_migration;
pub mod data_profiles;
pub mod data_quality;
mod dev_update_sources;
pub mod dev_updates;
pub mod evaluation;
pub mod events;
pub mod export;
pub mod file_input;
pub mod hardware_profile;
pub mod input_data;
pub mod input_dates;
pub mod input_future;
pub mod input_parse_utils;
pub mod input_series;
pub mod interval_capability;
pub mod intervals;
pub mod limits;
pub mod model_config;
pub mod model_details;
pub mod model_details_github;
mod model_details_http;
mod model_details_huggingface;
mod model_details_markdown;
pub mod model_listing;
pub mod model_manager;
pub mod nixtla_multiseries;
pub mod notes;
pub mod notes_cleanup;
mod notes_files;
mod notes_transaction;
mod notes_validation;
pub mod numeric_parse;
pub mod provenance;
pub mod provenance_types;
pub mod registry;
pub mod request_normalize;
pub mod result_validation;
pub mod scenario_context;
pub mod scenario_context_run;
pub mod scenario_percent;
pub mod scenarios;
pub mod selected_model;
pub mod selection_policy;
pub mod selection_tickets;
pub mod sidecar;
mod sidecar_auth;
mod sidecar_http;
pub mod sidecar_process;
mod sidecar_process_env;
pub mod sidecar_runtime;
mod sidecar_settings;
mod sidecar_spawn;
pub mod spreadsheet_mapping;
pub mod storage;
mod storage_backtests;
mod storage_index;
mod storage_io;
mod storage_paths;
mod storage_revision;
pub mod target_domain;
pub mod types;
pub mod validation;
mod validation_selection;
pub mod workbench_context;
pub mod workbench_drafts;
pub mod workbench_geometry;

#[cfg(test)]
mod auto_selection_request_tests;
#[cfg(test)]
mod file_input_tests;
#[cfg(test)]
mod input_data_tests;
#[cfg(test)]
mod registry_tests;
#[cfg(test)]
mod types_compat_tests;
#[cfg(test)]
mod validation_tests;
