pub mod catalog;
pub mod client_chronos;
mod client_http;
mod client_local_response;
mod client_local_structured;
pub mod client_nixtla;
mod client_nixtla_options;
mod client_nixtla_retry;
mod client_quantiles;
pub mod data_profiles;
pub mod data_quality;
pub mod evaluation;
pub mod export;
pub mod file_input;
pub mod hardware_profile;
pub mod input_data;
pub mod input_dates;
pub mod input_future;
pub mod input_parse_utils;
pub mod input_series;
pub mod intervals;
pub mod limits;
pub mod model_config;
pub mod model_details;
pub mod model_details_github;
pub mod model_listing;
pub mod model_manager;
pub mod nixtla_multiseries;
pub mod notes;
pub mod notes_cleanup;
mod notes_files;
pub mod numeric_parse;
pub mod registry;
pub mod request_normalize;
pub mod result_validation;
pub mod scenario_context;
pub mod scenario_context_run;
pub mod scenario_percent;
pub mod scenarios;
pub mod selected_model;
pub mod selection_policy;
pub mod sidecar;
mod sidecar_auth;
mod sidecar_http;
pub mod sidecar_process;
pub mod sidecar_runtime;
mod sidecar_settings;
mod sidecar_spawn;
pub mod spreadsheet_mapping;
pub mod storage;
mod storage_io;
mod storage_paths;
pub mod target_domain;
pub mod types;
pub mod validation;
pub mod workbench_context;
pub mod workbench_drafts;
pub mod workbench_geometry;

#[cfg(test)]
mod file_input_tests;
#[cfg(test)]
mod input_data_tests;
#[cfg(test)]
mod registry_tests;
#[cfg(test)]
mod validation_tests;
