pub mod agent_local;
pub mod api_keys;
pub mod codex_client;
pub mod codex_oauth;
pub mod compress;
pub mod config;
pub mod dev_mode;
pub mod env_detect;
pub mod favorite_models;
pub mod file_watcher;
pub mod forecast;
pub mod gateway;
pub mod git;
pub mod git_context;
pub mod gpu_detect;
pub mod gpu_vram;
pub mod link_preview;
pub mod llm;
pub mod mcp_bridge;
pub mod mcp_oauth;
pub mod ollama_env;
pub mod ollama_kill;
#[cfg(test)]
mod ollama_kill_tests;
pub mod ollama_lifecycle;
pub mod ollama_port;
pub mod ollama_ps;
pub mod paths;
pub mod personality_injection;
pub mod reasoning;
#[cfg(test)]
mod reasoning_tests;
pub mod scheduler;
pub mod search;
pub mod searxng;
pub mod stream_utils;
pub mod terminal;
pub mod vault;
