use super::ForecastModelSpec;

pub const CHRONOS_BOLT_TINY: ForecastModelSpec = ForecastModelSpec {
    id: "chronos-bolt-tiny",
    provider_id: "chronos",
    family_id: "chronos-bolt",
    display_name: "Chronos-Bolt Tiny",
    params: "9M",
    size_mb: 35,
    ram_mb: 150,
    vram_mb: Some(60),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: false,
    covariates: false,
    horizon_max: 1000,
    frequencies: "10S à Y",
    hf_repo: Some("amazon/chronos-bolt-tiny"),
    hf_revision: Some("a0e552de83495b5c28c14c71c374f3e33280b340"),
    github_repo: None,
    github_revision: None,
    is_cloud: false,
};

pub const CHRONOS_BOLT_MINI: ForecastModelSpec = ForecastModelSpec {
    id: "chronos-bolt-mini",
    provider_id: "chronos",
    family_id: "chronos-bolt",
    display_name: "Chronos-Bolt Mini",
    params: "21M",
    size_mb: 85,
    ram_mb: 350,
    vram_mb: Some(120),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: false,
    covariates: false,
    horizon_max: 1000,
    frequencies: "10S à Y",
    hf_repo: Some("amazon/chronos-bolt-mini"),
    hf_revision: Some("251268337516a88e253628c43e1d26ec577b376b"),
    github_repo: None,
    github_revision: None,
    is_cloud: false,
};

pub const CHRONOS_BOLT_SMALL: ForecastModelSpec = ForecastModelSpec {
    id: "chronos-bolt-small",
    provider_id: "chronos",
    family_id: "chronos-bolt",
    display_name: "Chronos-Bolt Small",
    params: "48M",
    size_mb: 191,
    ram_mb: 750,
    vram_mb: Some(280),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: false,
    covariates: false,
    horizon_max: 1000,
    frequencies: "10S à Y",
    hf_repo: Some("amazon/chronos-bolt-small"),
    hf_revision: Some("772f3d25d38aec6d914c8949dab4462e2d46f5d8"),
    github_repo: None,
    github_revision: None,
    is_cloud: false,
};

pub const CHRONOS_BOLT_BASE: ForecastModelSpec = ForecastModelSpec {
    id: "chronos-bolt-base",
    provider_id: "chronos",
    family_id: "chronos-bolt",
    display_name: "Chronos-Bolt Base",
    params: "205M",
    size_mb: 821,
    ram_mb: 3200,
    vram_mb: Some(1200),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: false,
    covariates: false,
    horizon_max: 1000,
    frequencies: "10S à Y",
    hf_repo: Some("amazon/chronos-bolt-base"),
    hf_revision: Some("5d9f166d69f47aef3401367a7b842e78fe97b121"),
    github_repo: None,
    github_revision: None,
    is_cloud: false,
};

pub const CHRONOS_2: ForecastModelSpec = ForecastModelSpec {
    id: "chronos-2",
    provider_id: "chronos",
    family_id: "chronos-2",
    display_name: "Chronos-2",
    params: "120M",
    size_mb: 478,
    ram_mb: 2400,
    vram_mb: Some(1000),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: false,
    covariates: true,
    horizon_max: 1024,
    frequencies: "10S à Y",
    hf_repo: Some("amazon/chronos-2"),
    hf_revision: Some("29ec3766d36d6f73f0696f85560a422f50e8498c"),
    github_repo: Some("amazon-science/chronos-forecasting"),
    github_revision: Some("fd533389c300660f9d8e3a00fcb29e4ca1174745"),
    is_cloud: false,
};
