use super::ForecastModelSpec;

pub const CHRONOS_BOLT_TINY: ForecastModelSpec = ForecastModelSpec {
    id: "chronos-bolt-tiny",
    provider_id: "chronos",
    family_id: "chronos-bolt",
    display_name: "Chronos-Bolt Tiny",
    params: "9M",
    size_mb: 35,
    ram_mb: 150,
    vram_mb: Some(60),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: false,
    covariates: false,
    horizon_max: 1000,
    frequencies: "10S à Y",
    hf_repo: Some("amazon/chronos-bolt-tiny"),
    hf_revision: None,
    github_repo: None,
    github_revision: None,
    is_cloud: false,
};

pub const CHRONOS_BOLT_MINI: ForecastModelSpec = ForecastModelSpec {
    id: "chronos-bolt-mini",
    provider_id: "chronos",
    family_id: "chronos-bolt",
    display_name: "Chronos-Bolt Mini",
    params: "21M",
    size_mb: 85,
    ram_mb: 350,
    vram_mb: Some(120),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: false,
    covariates: false,
    horizon_max: 1000,
    frequencies: "10S à Y",
    hf_repo: Some("amazon/chronos-bolt-mini"),
    hf_revision: None,
    github_repo: None,
    github_revision: None,
    is_cloud: false,
};

pub const CHRONOS_BOLT_SMALL: ForecastModelSpec = ForecastModelSpec {
    id: "chronos-bolt-small",
    provider_id: "chronos",
    family_id: "chronos-bolt",
    display_name: "Chronos-Bolt Small",
    params: "48M",
    size_mb: 191,
    ram_mb: 750,
    vram_mb: Some(280),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: false,
    covariates: false,
    horizon_max: 1000,
    frequencies: "10S à Y",
    hf_repo: Some("amazon/chronos-bolt-small"),
    hf_revision: None,
    github_repo: None,
    github_revision: None,
    is_cloud: false,
};

pub const CHRONOS_BOLT_BASE: ForecastModelSpec = ForecastModelSpec {
    id: "chronos-bolt-base",
    provider_id: "chronos",
    family_id: "chronos-bolt",
    display_name: "Chronos-Bolt Base",
    params: "205M",
    size_mb: 821,
    ram_mb: 3200,
    vram_mb: Some(1200),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: false,
    covariates: false,
    horizon_max: 1000,
    frequencies: "10S à Y",
    hf_repo: Some("amazon/chronos-bolt-base"),
    hf_revision: None,
    github_repo: None,
    github_revision: None,
    is_cloud: false,
};

pub const CHRONOS_2: ForecastModelSpec = ForecastModelSpec {
    id: "chronos-2",
    provider_id: "chronos",
    family_id: "chronos-2",
    display_name: "Chronos-2",
    params: "120M",
    size_mb: 478,
    ram_mb: 2400,
    vram_mb: Some(1000),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: true,
    covariates: true,
    horizon_max: 1024,
    frequencies: "10S à Y",
    hf_repo: Some("amazon/chronos-2"),
    hf_revision: None,
    github_repo: Some("amazon-science/chronos-forecasting"),
    github_revision: None,
    is_cloud: false,
};
