use super::ForecastModelSpec;

pub const TOTO_2_0_4M: ForecastModelSpec = ForecastModelSpec {
    id: "toto-2.0-4m",
    provider_id: "datadog",
    family_id: "toto-2",
    display_name: "Toto 2.0 4M",
    params: "4M",
    size_mb: 16,
    ram_mb: 300,
    vram_mb: Some(150),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: true,
    covariates: false,
    horizon_max: 2048,
    frequencies: "Toutes",
    hf_repo: Some("Datadog/Toto-2.0-4m"),
    hf_revision: None,
    github_repo: Some("DataDog/toto"),
    github_revision: None,
    is_cloud: false,
};

pub const TOTO_2_0_22M: ForecastModelSpec = ForecastModelSpec {
    id: "toto-2.0-22m",
    provider_id: "datadog",
    family_id: "toto-2",
    display_name: "Toto 2.0 22M",
    params: "22M",
    size_mb: 84,
    ram_mb: 650,
    vram_mb: Some(320),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: true,
    covariates: false,
    horizon_max: 2048,
    frequencies: "Toutes",
    hf_repo: Some("Datadog/Toto-2.0-22m"),
    hf_revision: None,
    github_repo: Some("DataDog/toto"),
    github_revision: None,
    is_cloud: false,
};

pub const TOTO_2_0_313M: ForecastModelSpec = ForecastModelSpec {
    id: "toto-2.0-313m",
    provider_id: "datadog",
    family_id: "toto-2",
    display_name: "Toto 2.0 313M",
    params: "313M",
    size_mb: 1200,
    ram_mb: 4200,
    vram_mb: Some(1800),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: true,
    covariates: false,
    horizon_max: 2048,
    frequencies: "Toutes",
    hf_repo: Some("Datadog/Toto-2.0-313m"),
    hf_revision: None,
    github_repo: Some("DataDog/toto"),
    github_revision: None,
    is_cloud: false,
};

pub const TOTO_2_0_1B: ForecastModelSpec = ForecastModelSpec {
    id: "toto-2.0-1b",
    provider_id: "datadog",
    family_id: "toto-2",
    display_name: "Toto 2.0 1B",
    params: "1B",
    size_mb: 3900,
    ram_mb: 9000,
    vram_mb: Some(5200),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: true,
    covariates: false,
    horizon_max: 2048,
    frequencies: "Toutes",
    hf_repo: Some("Datadog/Toto-2.0-1B"),
    hf_revision: None,
    github_repo: Some("DataDog/toto"),
    github_revision: None,
    is_cloud: false,
};

pub const TOTO_2_0_2_5B: ForecastModelSpec = ForecastModelSpec {
    id: "toto-2.0-2.5b",
    provider_id: "datadog",
    family_id: "toto-2",
    display_name: "Toto 2.0 2.5B",
    params: "2.5B",
    size_mb: 9100,
    ram_mb: 18000,
    vram_mb: Some(11000),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: true,
    covariates: false,
    horizon_max: 2048,
    frequencies: "Toutes",
    hf_repo: Some("Datadog/Toto-2.0-2.5B"),
    hf_revision: None,
    github_repo: Some("DataDog/toto"),
    github_revision: None,
    is_cloud: false,
};
