use super::ForecastModelSpec;

pub const TABPFN_TS: ForecastModelSpec = build(
    "tabpfn-ts",
    "tabpfn-ts",
    "TabPFN-TS",
    "priorlabs",
    "Toutes",
    "—",
    3,
    120,
    Some(60),
    None,
    "PriorLabs/tabpfn-time-series",
);
pub const TABPFN_TS_3: ForecastModelSpec = build(
    "tabpfn-ts-3",
    "tabpfn-ts",
    "TabPFN-TS-3",
    "priorlabs",
    "Toutes",
    "—",
    3,
    120,
    Some(60),
    None,
    "PriorLabs/tabpfn-time-series",
);
pub const TIREX: ForecastModelSpec = ForecastModelSpec {
    id: "tirex-35m",
    provider_id: "nxai",
    family_id: "tirex",
    display_name: "TiRex 35M",
    params: "35M",
    size_mb: 140,
    ram_mb: 900,
    vram_mb: Some(420),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: true,
    covariates: true,
    horizon_max: 1024,
    frequencies: "Toutes",
    hf_repo: Some("NX-AI/TiRex"),
    hf_revision: None,
    github_repo: Some("NX-AI/TiRex"),
    github_revision: None,
    is_cloud: false,
};
pub const KAIROS_10M: ForecastModelSpec = build(
    "kairos-10m",
    "kairos",
    "Kairos 10M",
    "foundation-model-research",
    "Toutes",
    "10M",
    38,
    320,
    Some(140),
    Some("mldi-lab/Kairos_10m"),
    "foundation-model-research/Kairos",
);
pub const KAIROS_23M: ForecastModelSpec = build(
    "kairos-23m",
    "kairos",
    "Kairos 23M",
    "foundation-model-research",
    "Toutes",
    "23M",
    88,
    520,
    Some(220),
    Some("mldi-lab/Kairos_23m"),
    "foundation-model-research/Kairos",
);
pub const KAIROS_50M: ForecastModelSpec = build(
    "kairos-50m",
    "kairos",
    "Kairos 50M",
    "foundation-model-research",
    "Toutes",
    "50M",
    191,
    980,
    Some(420),
    Some("mldi-lab/Kairos_50m"),
    "foundation-model-research/Kairos",
);
pub const SUNDIAL_128M: ForecastModelSpec = build(
    "sundial-128m",
    "sundial",
    "Sundial 128M",
    "thuml",
    "Toutes",
    "128M",
    490,
    2400,
    Some(1000),
    Some("thuml/sundial-base-128m"),
    "thuml/Sundial",
);

const fn build(
    id: &'static str,
    family_id: &'static str,
    display_name: &'static str,
    provider_id: &'static str,
    frequencies: &'static str,
    params: &'static str,
    size_mb: u32,
    ram_mb: u32,
    vram_mb: Option<u32>,
    hf_repo: Option<&'static str>,
    github_repo: &'static str,
) -> ForecastModelSpec {
    ForecastModelSpec {
        id,
        provider_id,
        family_id,
        display_name,
        params,
        size_mb,
        ram_mb,
        vram_mb,
        cpu_supported: true,
        gpu_supported: true,
        multivariate: true,
        covariates: true,
        horizon_max: 1024,
        frequencies,
        hf_repo,
        hf_revision: None,
        github_repo: Some(github_repo),
        github_revision: None,
        is_cloud: false,
    }
}
