use super::ForecastModelSpec;

pub const FLOWSTATE_R1: ForecastModelSpec = ForecastModelSpec {
    id: "flowstate-r1",
    provider_id: "ibm",
    family_id: "flowstate",
    display_name: "FlowState R1",
    params: "9M",
    size_mb: 37,
    ram_mb: 650,
    vram_mb: Some(260),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: true,
    covariates: false,
    horizon_max: 4096,
    frequencies: "Toutes",
    hf_repo: Some("ibm-granite/granite-timeseries-flowstate-r1"),
    hf_revision: None,
    github_repo: Some("ibm-granite/granite-tsfm"),
    github_revision: None,
    is_cloud: false,
};

pub const FLOWSTATE_R1_1: ForecastModelSpec = ForecastModelSpec {
    id: "flowstate-r1.1",
    provider_id: "ibm",
    family_id: "flowstate",
    display_name: "FlowState R1.1",
    params: "18.5M",
    size_mb: 37,
    ram_mb: 750,
    vram_mb: Some(320),
    cpu_supported: true,
    gpu_supported: true,
    multivariate: true,
    covariates: false,
    horizon_max: 4096,
    frequencies: "Toutes",
    hf_repo: Some("ibm-granite/granite-timeseries-flowstate-r1"),
    hf_revision: Some("r1.1"),
    github_repo: Some("ibm-granite/granite-tsfm"),
    github_revision: None,
    is_cloud: false,
};
