use super::ForecastModelSpec;

pub const TIMEGPT_2_MINI: ForecastModelSpec = ForecastModelSpec {
    id: "timegpt-2-mini",
    provider_id: "nixtla",
    family_id: "timegpt-2",
    display_name: "TimeGPT-2 Mini",
    params: "—",
    size_mb: 0,
    ram_mb: 0,
    vram_mb: None,
    cpu_supported: false,
    gpu_supported: false,
    multivariate: true,
    covariates: true,
    horizon_max: 5000,
    frequencies: "T à Y",
    hf_repo: None,
    hf_revision: None,
    github_repo: None,
    github_revision: None,
    is_cloud: true,
};

pub const TIMEGPT_2_STANDARD: ForecastModelSpec = ForecastModelSpec {
    id: "timegpt-2-standard",
    provider_id: "nixtla",
    family_id: "timegpt-2",
    display_name: "TimeGPT-2 Standard",
    params: "—",
    size_mb: 0,
    ram_mb: 0,
    vram_mb: None,
    cpu_supported: false,
    gpu_supported: false,
    multivariate: true,
    covariates: true,
    horizon_max: 5000,
    frequencies: "T à Y",
    hf_repo: None,
    hf_revision: None,
    github_repo: None,
    github_revision: None,
    is_cloud: true,
};

pub const TIMEGPT_2_PRO: ForecastModelSpec = ForecastModelSpec {
    id: "timegpt-2-pro",
    provider_id: "nixtla",
    family_id: "timegpt-2",
    display_name: "TimeGPT-2 Pro",
    params: "—",
    size_mb: 0,
    ram_mb: 0,
    vram_mb: None,
    cpu_supported: false,
    gpu_supported: false,
    multivariate: true,
    covariates: true,
    horizon_max: 5000,
    frequencies: "T à Y",
    hf_repo: None,
    hf_revision: None,
    github_repo: None,
    github_revision: None,
    is_cloud: true,
};

pub const TIMEGPT_2_1: ForecastModelSpec = ForecastModelSpec {
    id: "timegpt-2.1",
    provider_id: "nixtla",
    family_id: "timegpt-2",
    display_name: "TimeGPT-2.1",
    params: "—",
    size_mb: 0,
    ram_mb: 0,
    vram_mb: None,
    cpu_supported: false,
    gpu_supported: false,
    multivariate: true,
    covariates: true,
    horizon_max: 5000,
    frequencies: "T à Y",
    hf_repo: None,
    hf_revision: None,
    github_repo: None,
    github_revision: None,
    is_cloud: true,
};
