use super::ForecastProviderSpec;

pub const FORECAST_PROVIDERS: &[ForecastProviderSpec] = &[
    ForecastProviderSpec {
        id: "chronos",
        display_name: "Amazon Chronos",
        category: "forecast",
        base_url: "http://localhost:12000",
        signup_url: "https://huggingface.co/amazon/chronos-2",
        free_tier_label: "Local",
        short_description: "Famille Chronos locale pour prévisions temporelles.",
        short_description_en: "Local Chronos family for time-series forecasting.",
        requires_api_key: false,
    },
    ForecastProviderSpec {
        id: "google",
        display_name: "Google TimesFM",
        category: "forecast",
        base_url: "https://huggingface.co/google",
        signup_url: "https://huggingface.co/google/timesfm-2.5-200m-pytorch",
        free_tier_label: "Local",
        short_description: "TimesFM 2.5 local open source.",
        short_description_en: "Open local TimesFM 2.5.",
        requires_api_key: false,
    },
    ForecastProviderSpec {
        id: "nixtla",
        display_name: "Nixtla (TimeGPT-2)",
        category: "forecast",
        base_url: "https://api.nixtla.io",
        signup_url: "https://dashboard.nixtla.io",
        free_tier_label: "Preview / API",
        short_description: "Famille cloud TimeGPT-2.x / 2.1.",
        short_description_en: "Cloud TimeGPT-2.x / 2.1 family.",
        requires_api_key: true,
    },
    ForecastProviderSpec {
        id: "datadog",
        display_name: "Datadog Toto 2.0",
        category: "forecast",
        base_url: "https://huggingface.co/Datadog",
        signup_url: "https://huggingface.co/Datadog/Toto-2.0-4m",
        free_tier_label: "Local",
        short_description: "Foundation models Toto 2.0 orientés séries et observabilité.",
        short_description_en: "Toto 2.0 foundation models for time series and observability.",
        requires_api_key: false,
    },
    ForecastProviderSpec {
        id: "salesforce",
        display_name: "Salesforce MOIRAI 2.0",
        category: "forecast",
        base_url: "https://huggingface.co/Salesforce",
        signup_url: "https://huggingface.co/Salesforce/moirai-2.0-R-small",
        free_tier_label: "Local",
        short_description: "Famille MOIRAI 2.0 pour forecasting probabiliste.",
        short_description_en: "MOIRAI 2.0 family for probabilistic forecasting.",
        requires_api_key: false,
    },
    ForecastProviderSpec {
        id: "ibm",
        display_name: "IBM FlowState",
        category: "forecast",
        base_url: "https://huggingface.co/ibm-granite",
        signup_url: "https://huggingface.co/ibm-granite/granite-timeseries-flowstate-r1",
        free_tier_label: "Local",
        short_description: "FlowState local pour séries temporelles.",
        short_description_en: "Local FlowState for time series.",
        requires_api_key: false,
    },
    ForecastProviderSpec {
        id: "priorlabs",
        display_name: "PriorLabs TabPFN-TS",
        category: "forecast",
        base_url: "https://github.com/PriorLabs/tabpfn-time-series",
        signup_url: "https://github.com/PriorLabs/tabpfn-time-series",
        free_tier_label: "Local",
        short_description: "Famille TabPFN-TS pour prévision zéro entraînement.",
        short_description_en: "TabPFN-TS family for zero-training forecasting.",
        requires_api_key: false,
    },
    ForecastProviderSpec {
        id: "nxai",
        display_name: "NX-AI TiRex",
        category: "forecast",
        base_url: "https://huggingface.co/NX-AI",
        signup_url: "https://huggingface.co/NX-AI/TiRex",
        free_tier_label: "Local",
        short_description: "TiRex pour forecasting quantile et zéro-shot.",
        short_description_en: "TiRex for zero-shot and quantile forecasting.",
        requires_api_key: false,
    },
    ForecastProviderSpec {
        id: "foundation-model-research",
        display_name: "Foundation Model Research Kairos",
        category: "forecast",
        base_url: "https://github.com/foundation-model-research/Kairos",
        signup_url: "https://github.com/foundation-model-research/Kairos",
        free_tier_label: "Local",
        short_description: "Famille Kairos pour séries temporelles multi-régimes.",
        short_description_en: "Kairos family for multi-regime time series.",
        requires_api_key: false,
    },
    ForecastProviderSpec {
        id: "thuml",
        display_name: "THUML Sundial",
        category: "forecast",
        base_url: "https://github.com/thuml/Sundial",
        signup_url: "https://github.com/thuml/Sundial",
        free_tier_label: "Local",
        short_description: "Sundial pour forecasting probabiliste zéro-shot.",
        short_description_en: "Sundial for zero-shot probabilistic forecasting.",
        requires_api_key: false,
    },
];
